# Generated by Django 2.2.1 on 2019-06-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date',
            field=models.CharField(max_length=128),
        ),
    ]
